name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Ref
        id: vars
        run: |
          tag="${GITHUB_REF#refs/*/v}"
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"

      - name: Create rock file
        uses: Kong/kong-pongo-action@v1
        with:
          pongo_version: master
        run: |
          mkdir -p ./rocks
          pongo pack
          mv kong-plugin-*.all.rock ./rocks

      - name: Prep release docs
        run: |
          mkdir -p docs
          cp README.md "docs/${{ github.event.repository.name }}-README-${{ steps.vars.outputs.tag }}.md"
          cp CHANGELOG.md "docs/${{ github.event.repository.name }}-CHANGELOG-${{ steps.vars.outputs.tag }}.md"

      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ./docs
          output_dir: ./release-files/
          build_html: false

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-files/*
            rocks/*
        env:
          # Uses the built-in token, constrained by permissions above
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



name: Release

on:
  push:
    tags:
      - "v*.*.*"

name: Release

on:
  push:
    tags:
      - "v*.*.*"

# Limit the token to exactly what is required for releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Ref
        id: vars
        run: |
          tag="${GITHUB_REF#refs/*/v}"
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"

      - name: Create rock file
        uses: Kong/kong-pongo-action@v1
        with:
          pongo_version: master
        run: |
          mkdir -p ./rocks
          pongo pack
          mv kong-plugin-*.all.rock ./rocks

      - name: Prep release docs
        run: |
          mkdir -p docs
          cp README.md "docs/${{ github.event.repository.name }}-README-${{ steps.vars.outputs.tag }}.md"
          cp CHANGELOG.md "docs/${{ github.event.repository.name }}-CHANGELOG-${{ steps.vars.outputs.tag }}.md"

      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ./docs
          output_dir: ./release-files/
          build_html: false

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-files/*
            rocks/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
